name: Static analysis
on:
  pull_request:
  push:
    branches:
      - master
      - stable*

permissions:
  contents: read

jobs:
  static-psalm-analysis:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ocp-version: [ 'v25.0.0']
        php-version: [ '7.4' ]
        include:
          - ocp-version: 'v25.0.0'
            php-version: '8.0'
          - ocp-version: 'v25.0.0'
            php-version: '8.1'

    name: Nextcloud ${{ matrix.ocp-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - name: Install dependencies
        run: composer i

      - name: Install dependencies
        run: composer require --dev nextcloud/ocp:${{ matrix.ocp-version }}

      - name: Run coding standards check
        run: composer run psalm
